name: ci
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          yarn install --no-immutable
          bun install --frozen-lockfile=false
